In [12]:
import pandas as pd
import numpy as np

In [13]:
import torch

In [15]:
new_arr = np.array([1,2,3])

In [16]:
new_arr.dtype

dtype('int32')

In [17]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
my_tensor = torch.FloatTensor(new_arr)

In [22]:
my_tensor.dtype

torch.float32

In [23]:
torch.empty(2,2)

tensor([[4.7351e+22, 1.9684e-19],
        [2.0959e-19, 5.0833e+31]])

In [25]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [26]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [30]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [31]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [32]:
my_tensor = torch.tensor([1,2,3])

In [33]:
my_tensor.dtype

torch.int64

In [34]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.rand(4,3)

tensor([[0.6633, 0.3001, 0.1348],
        [0.3705, 0.9584, 0.3035],
        [0.8015, 0.2141, 0.2579],
        [0.3208, 0.8862, 0.4175]])

In [37]:
torch.randn(4,3)

tensor([[-0.9721,  0.8358, -0.7128],
        [-0.4876, -1.4717, -0.3263],
        [-0.2083,  0.2820,  0.5191],
        [-0.1868, -0.7456,  2.3686]])

In [40]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[10,  7,  4,  7,  5],
        [ 6, 10,  2,  0,  7],
        [ 5,  4,  8,  5,  1],
        [ 6,  9,  4,  2,  9],
        [ 3,  5,  9,  7,  6]])

In [42]:
x = torch.zeros(2,5)

In [43]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [44]:
torch.rand_like(x)

tensor([[0.8882, 0.2177, 0.6192, 0.6425, 0.5640],
        [0.8920, 0.0238, 0.3622, 0.6472, 0.3069]])

In [45]:
torch.randn_like(x)

tensor([[ 0.6083, -1.2456, -0.0191, -0.0053,  0.0633],
        [-0.9612,  1.1679,  0.2201, -0.8592, -0.6324]])

In [47]:
torch.randint_like(x,low=0,high=11)

tensor([[9., 6., 4., 0., 5.],
        [0., 6., 2., 1., 2.]])

In [50]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])